In [1]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

#Answer: Here's how you can create a 3x3 NumPy array with random integers and then interchange its rows and columns:

#import numpy as np

# Create a 3x3 array with random integers between 1 and 100
#arr = np.random.randint(1, 101, size=(3, 3))
#print("Original array:")
#print(arr)

# Interchange rows and columns (transpose the array)
#transposed_arr = arr.T
#print("\nTransposed array:")
#print(transposed_arr)

#In this code:

#1. We import the NumPy library.
#2. We create a 3x3 array arr with random integers between 1 and 100 using np.random.randint.
#3. We print the original array.
#4. We interchange the rows and columns of the array by taking its transpose using the .T attribute.
#5. We print the transposed array.

#When you run this code, you'll see the original array and the transposed array printed out. The rows of the original array become the columns of the transposed array, and vice versa.

In [2]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

#Answer: Here's how you can generate a 1D NumPy array and reshape it into different forms:


#import numpy as np

# Generate a 1D array with 10 elements
#arr_1d = np.arange(1, 11)
#print("Original 1D array:")
#print(arr_1d)

# Reshape into a 2x5 array
#arr_2x5 = arr_1d.reshape(2, 5)
#print("\nReshaped 2x5 array:")
#print(arr_2x5)

# Reshape into a 5x2 array
#arr_5x2 = arr_1d.reshape(5, 2)
#print("\nReshaped 5x2 array:")
#print(arr_5x2)

#In this code:

#1. We import the NumPy library.
#2. We generate a 1D array arr_1d with 10 elements using np.arange.
#3. We print the original 1D array.
#4. We reshape the 1D array into a 2x5 array using the reshape method.
#5. We print the reshaped 2x5 array.
#6. We reshape the original 1D array into a 5x2 array using the reshape method.
#7. We print the reshaped 5x2 array.

#When you run this code, you'll see the original 1D array and the reshaped 2x5 and 5x2 arrays printed out. The elements are rearranged to fit the new shapes.

In [3]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

#Answer: Here's how you can create a 4x4 NumPy array with random float values and add a border of zeros around it:

#import numpy as np

# Create a 4x4 array with random float values
#arr = np.random.rand(4, 4)
#print("Original 4x4 array:")
#print(arr)

# Add a border of zeros around the array
#bordered_arr = np.pad(arr, 1, mode='constant')
#print("\n6x6 array with zero border:")
#print(bordered_arr)

#In this code:

#1. We import the NumPy library.
#2. We create a 4x4 array arr with random float values between 0 and 1 using np.random.rand.
#3. We print the original 4x4 array.
#4. We add a border of zeros around the array using np.pad. The pad_width parameter is set to 1, which means one layer of zeros is added around the array. The mode parameter is set to 'constant', which means the border is filled with a constant value (zero in this case).
#5. We print the resulting 6x6 array with the zero border.

#When you run this code, you'll see the original 4x4 array and the 6x6 array with the zero border printed out. The border of zeros surrounds the original array.

In [4]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

#Answer: I can help with that! Here's how you can create an array of integers from 10 to 60 with a step of 5 using NumPy:

#import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
#arr = np.arange(10, 61, 5)
#print(arr)

#In this code:

#1. We import the NumPy library.
#2. We use np.arange to create an array of integers. The parameters are:
    #- start: 10 (the starting value)
    #- stop: 61 (the end value, which is exclusive, so we use 61 to include 60)
    #- step: 5 (the increment between values)
#3. We print the resulting array.

#When you run this code, you'll see the following output:

#[10 15 20 25 30 35 40 45 50 55 60]

#This array contains integers from 10 to 60 with a step of 5.

In [5]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

#Answer: Here's how you can create a NumPy array of strings and apply different case transformations to each element:


#import numpy as np

# Create a NumPy array of strings
#arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
#uppercase = arr.upper()
#lowercase = arr.lower()
#title_case = arr.title()
#swapcase = arr.swapcase()
#capitalize = np.array([word.capitalize() for word in arr])

# Print the results
#print("Original array:")
#print(arr)
#print("\nUppercase:")
#print(uppercase)
#print("\nLowercase:")
#print(lowercase)
#print("\nTitle case:")
#print(title_case)
#print("\nSwapcase:")
#print(swapcase)
#print("\nCapitalize:")
#print(capitalize)

#In this code:

#1. We import the NumPy library.
#2. We create a NumPy array arr containing the strings 'python', 'numpy', and 'pandas'.
#3. We apply different case transformations using various string methods:
    #- upper(): converts to uppercase
    #- lower(): converts to lowercase
    #- title(): converts to title case (first letter capitalized, rest lowercase)
    #- swapcase(): swaps case (uppercase becomes lowercase, and vice versa)
    #- capitalize(): capitalizes the first letter of each word (used with a list comprehension)
#4. We print the original array and the transformed arrays.

#When you run this code, you'll see the original array and the arrays with different case transformations printed out.

In [6]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

#Answer: Here's how you can generate a NumPy array of words and insert a space between each character of every word:


#import numpy as np

# Generate a NumPy array of words
#words = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
#spaced_words = np.array([' '.join(word) for word in words])

#print(spaced_words)

#In this code:

#1. We import the NumPy library.
#2. We generate a NumPy array words containing the words 'hello', 'world', 'numpy', and 'array'.
#3. We use a list comprehension to insert a space between each character of every word. The join() method is used to concatenate the characters with spaces in between.
#4. We print the resulting array spaced_words.

#When you run this code, you'll see the following output:

#['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']

#This array contains the words with spaces between each character.

In [7]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

#Answer: I can help with that! Here's how you can create two 2D NumPy arrays and perform element-wise operations:

#import numpy as np

# Create two 2D NumPy arrays
#arr1 = np.array([[1, 2], [3, 4]])
#arr2 = np.array([[5, 6], [7, 8]])

# Perform element-wise operations
#addition = arr1 + arr2
#subtraction = arr1 - arr2
#multiplication = arr1 * arr2
#division = arr1 / arr2

# Print the results
#print("Array 1:")
#print(arr1)
#print("\nArray 2:")
#print(arr2)
#print("\nElement-wise addition:")
#print(addition)
#print("\nElement-wise subtraction:")
#print(subtraction)
#print("\nElement-wise multiplication:")
#print(multiplication)
#print("\nElement-wise division:")
#print(division)

#In this code:

#1. We import the NumPy library.
#2. We create two 2D NumPy arrays arr1 and arr2.
#3. We perform element-wise operations using the corresponding operators:
    #- + for addition
    #- - for subtraction
    #- * for multiplication
    #- / for division
#4. We print the original arrays and the results of the element-wise operations.

#When you run this code, you'll see the original arrays and the results of the element-wise operations printed out. The operations are performed element-wise, meaning that corresponding elements in the input arrays are combined to produce the output array.

In [8]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

#Answer: Here's how you can create a 5x5 identity matrix using NumPy and extract its diagonal elements:

#import numpy as np

# Create a 5x5 identity matrix
#identity_matrix = np.eye(5)
#print("5x5 Identity Matrix:")
#print(identity_matrix)

# Extract diagonal elements
#diagonal_elements = np.diag(identity_matrix)
#print("\nDiagonal Elements:")
#print(diagonal_elements)

#In this code:

#1. We import the NumPy library.
#2. We create a 5x5 identity matrix using np.eye(5).
#3. We print the identity matrix.
#4. We extract the diagonal elements using np.diag().
#5. We print the diagonal elements.

#When you run this code, you'll see the 5x5 identity matrix and its diagonal elements printed out. The diagonal elements of an identity matrix are always 1.

#Output:

#5x5 Identity Matrix:
#[[1. 0. 0. 0. 0.]
 #[0. 1. 0. 0. 0.]
 #[0. 0. 1. 0. 0.]
 #[0. 0. 0. 1. 0.]
 #[0. 0. 0. 0. 1.]]

#Diagonal Elements:
#[1. 1. 1. 1. 1.]

In [9]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

#Answer: Here's how you can generate a NumPy array of 100 random integers and find the prime numbers:

#import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
#random_array = np.random.randint(0, 1001, size=100)
#print("Random Array:")
#print(random_array)

# Function to check if a number is prime
#def is_prime(n):
    #if n < 2:
        #return False
    #for i in range(2, int(np.sqrt(n)) + 1):
        #if n % i == 0:
            #return False
    #return True

# Find prime numbers in the array
#prime_numbers = random_array[np.vectorize(is_prime)(random_array)]
#print("\nPrime Numbers:")
#print(prime_numbers)

#In this code:

#1. We import the NumPy library.
#2. We generate a NumPy array random_array of 100 random integers between 0 and 1000 using np.random.randint.
#3. We define a function is_prime to check if a number is prime.
#4. We use np.vectorize to apply the is_prime function to each element in the array.
#5. We use boolean indexing to get the prime numbers from the array.
#6. We print the random array and the prime numbers.

#When you run this code, you'll see the random array and the prime numbers printed out. The prime numbers are the numbers in the array that are divisible only by 1 and themselves.

In [10]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

#Answer: Here's how you can create a NumPy array representing daily temperatures for a month and calculate the weekly averages:

#import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
#daily_temperatures = np.random.uniform(20, 30, size=30)
#print("Daily Temperatures:")
#print(daily_temperatures)

# Calculate weekly averages
#weekly_temperatures = [daily_temperatures[i:i+7].mean() for i in range(0, 30, 7)]
#print("\nWeekly Averages:")
#print(weekly_temperatures)

#In this code:

#1. We import the NumPy library.
#2. We create a NumPy array daily_temperatures representing daily temperatures for a month (30 days) using np.random.uniform.
#3. We calculate the weekly averages by slicing the array into weekly segments (7 days each) and applying the mean method.
#4. We print the daily temperatures and the weekly averages.

#When you run this code, you'll see the daily temperatures and the weekly averages printed out. The weekly averages are the mean temperatures for each week in the month.

#Note: This code assumes a 30-day month. If your month has a different number of days, adjust the array size and slicing accordingly.